CREATE TABLE USUARIO(
 nombre_usuario VARCHAR2(100) NOT NULL,
 contrasenia VARCHAR2 (100) NOT NULL CHECK (LENGTH(contrasenia) >= 8),
 email VARCHAR2(100) NOT NULL,
 fecha_hora_inicio DATE NOT NULL,
 UNIQUE(email),
 PRIMARY KEY (nombre_usuario)
 ); 

 CREATE TABLE PERFIL (
nombre VARCHAR2(100) NULL,
apellido1 VARCHAR2(100) NULL,
apellido2 VARCHAR2(100) NULL,
fecha_nacimiento DATE NULL,
numero_telefono VARCHAR2(14) NULL,
dni VARCHAR2(9) NOT NULL,
nombre_usuario VARCHAR2(100) NOT NULL,
UNIQUE (dni),
FOREIGN KEY (nombre_usuario) REFERENCES USUARIO (nombre_usuario),
PRIMARY KEY (nombre_usuario)
);

CREATE TABLE PERSONA (
id_persona NUMBER GENERATED ALWAYS AS IDENTITY,
datos VARCHAR2 (100) NOT NULL,
PRIMARY KEY (id_persona));

CREATE TABLE PELICULA (
titulo VARCHAR2(100) NOT NULL,
id_director NUMBER NOT NULL,
duracion VARCHAR2(100) NULL,
color VARCHAR2(100) NULL  CHECK(color IN('Color','Black and White') OR color IS NULL),
ratio VARCHAR2(100) NULL,
anio_estreno VARCHAR2(100) NULL,
calificacion_edad VARCHAR2(100) NULL,
pais VARCHAR2(100) NULL,
idioma VARCHAR2(100) NULL,
presupuesto VARCHAR2(100)  NULL,
ingresos VARCHAR2(100) NULL,
web_imdb VARCHAR2(100) NOT NULL,
puntuacion_imdb VARCHAR2(100) NOT NULL,
review_usuarios_imdb VARCHAR2(100) NULL,
review_criticos_imdb VARCHAR2(100) NULL,
votaciones_usuarios VARCHAR2(100) NULL,
numero_rostros VARCHAR2(100) NULL,
fb_like_director VARCHAR2(100) NOT NULL,
fb_like_reparto VARCHAR2(100) NOT NULL,
fb_like_pelicula VARCHAR2(100) NOT NULL,
FOREIGN KEY (id_director) REFERENCES PERSONA (id_persona),
PRIMARY KEY (titulo,id_director)
);

CREATE TABLE PROTAGONISTA (
ID_ACTOR INT NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
ID_DIRECTOR INT NOT NULL,
FOREIGN KEY (ID_ACTOR) REFERENCES PERSONA (ID_PERSONA),
FOREIGN KEY (TITULO,ID_DIRECTOR) REFERENCES PELICULA (TITULO,ID_DIRECTOR),
PRIMARY KEY (ID_ACTOR,TITULO,ID_DIRECTOR)
);

CREATE TABLE GENERO (
GENERO VARCHAR2(30) NOT NULL,
PRIMARY KEY (GENERO)
);

CREATE TABLE GENERO_PELICULA(
GENERO VARCHAR2(30) NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
ID_DIRECTOR INT NOT NULL,
FOREIGN KEY (TITULO,ID_DIRECTOR) REFERENCES PELICULA (TITULO,ID_DIRECTOR),
FOREIGN KEY (GENERO) REFERENCES GENERO (GENERO),
PRIMARY KEY (GENERO,TITULO, ID_DIRECTOR)
);

CREATE TABLE PALABRA_CLAVE (
PALABRA VARCHAR(50) NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
ID_DIRECTOR INT NOT NULL,
FOREIGN KEY (TITULO, ID_DIRECTOR) REFERENCES PELICULA (TITULO, ID_DIRECTOR),
PRIMARY KEY (PALABRA, TITULO, ID_DIRECTOR)
);

CREATE TABLE CONTRATO (
NOMBRE_USUARIO_CONTRATO VARCHAR2(100) NOT NULL,
TIPO_CONTRATO VARCHAR2(50) NOT NULL,
ID_CONTRATO VARCHAR2(16) NOT NULL,
DIRECCION_POSTAL VARCHAR2(100) NOT NULL,
CODIGO_POSTAL VARCHAR2(10) NOT NULL,
CIUDAD VARCHAR2(100) NOT NULL,
PAIS VARCHAR2(100) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE NULL,
FOREIGN KEY (NOMBRE_USUARIO_CONTRATO) REFERENCES PERFIL (NOMBRE_USUARIO),
PRIMARY KEY (ID_CONTRATO),
CONSTRAINT TIME_START_END CHECK ((FECHA_INICIO) <= (FECHA_FIN) OR FECHA_FIN IS NULL)
);

CREATE TABLE CLUB (
NOMBRE_CLUB VARCHAR2(60) NOT NULL,
NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
SLOGAN VARCHAR(100) NOT NULL,
VISTA VARCHAR2(50) NOT NULL CHECK(VISTA IN('Open','Closed')),
ESTADO VARCHAR(50) NOT NULL CHECK(ESTADO IN('Active','Inactive')),
FECHA_HORA_INICIO DATE NOT NULL,
FECHA_HORA_FIN DATE NULL,
FOREIGN KEY (NOMBRE_USUARIO) REFERENCES USUARIO (NOMBRE_USUARIO),
PRIMARY KEY (NOMBRE_CLUB),
CONSTRAINT TIME_START_END_Club CHECK (((FECHA_HORA_INICIO) <= (FECHA_HORA_FIN)) OR FECHA_HORA_FIN IS NULL)
);

CREATE TABLE MIEMBROS(
NOMBRE_CLUB VARCHAR2(60) NOT NULL,
NOMBRE_USUARIO_MIEMBRO VARCHAR2(100) NOT NULL,
FOREIGN KEY (NOMBRE_USUARIO_MIEMBRO) REFERENCES USUARIO (NOMBRE_USUARIO),
FOREIGN KEY (NOMBRE_CLUB) REFERENCES CLUB (NOMBRE_CLUB),
PRIMARY KEY (NOMBRE_CLUB, NOMBRE_USUARIO_MIEMBRO)
);

CREATE TABLE INVITACIONES(
NOMBRE_CLUB VARCHAR2(60) NOT NULL,
NOMBRE_USUARIO_INVITA VARCHAR2(100) NOT NULL,
NOMBRE_USUARIO_INVITADO VARCHAR(100) NOT NULL,
FECHA_HORA_INVITACION DATE NOT NULL,
MENSAJE_TEXTO_INVITACION VARCHAR2(1500) NOT NULL,
RESPUESTA VARCHAR2(1500) NULL CHECK(RESPUESTA IN('rejection','acceptance') or respuesta is null) ,
FECHA_HORA_RESPUESTA DATE NULL,
MENSAJE_TEXTO_RESPUESTA VARCHAR2(1500) NULL,
FOREIGN KEY (NOMBRE_USUARIO_INVITA,NOMBRE_CLUB) REFERENCES MIEMBROS(NOMBRE_USUARIO_MIEMBRO,NOMBRE_CLUB),
FOREIGN KEY (NOMBRE_USUARIO_INVITADO) REFERENCES USUARIO (NOMBRE_USUARIO),
PRIMARY KEY (NOMBRE_CLUB,NOMBRE_USUARIO_INVITA,NOMBRE_USUARIO_INVITADO,FECHA_HORA_INVITACION),
CONSTRAINT TIME_START_END_INVITACION CHECK (((FECHA_HORA_INVITACION) <= (FECHA_HORA_RESPUESTA)) OR FECHA_HORA_RESPUESTA IS NULL));

CREATE TABLE SOLICITUD(
NOMBRE_CLUB VARCHAR2(60) NOT NULL,
NOMBRE_USUARIO_SOLICITA VARCHAR2(100) NOT NULL,
NOMBRE_USUARIO_MIEMBRO VARCHAR2(100) NULL,
FECHA_HORA_SOLICITUD DATE NOT NULL,
MENSAJE_TEXTO_SOLICITUD VARCHAR2(100) NOT NULL,
RESPUESTA VARCHAR2(1500) NULL CHECK(RESPUESTA IN('rejection','acceptance') or respuesta is null),
FECHA_HORA_RESPUESTA DATE NULL,
MENSAJE_TEXTO_RESPUESTA VARCHAR2(1500) NULL,
FOREIGN KEY (NOMBRE_CLUB,NOMBRE_USUARIO_MIEMBRO) REFERENCES MIEMBROS (NOMBRE_CLUB,NOMBRE_USUARIO_MIEMBRO),
FOREIGN KEY (NOMBRE_USUARIO_SOLICITA) REFERENCES USUARIO (NOMBRE_USUARIO),
PRIMARY KEY (NOMBRE_CLUB,NOMBRE_USUARIO_SOLICITA,FECHA_HORA_SOLICITUD),
CONSTRAINT TIME_START_END_SOLICITUD CHECK (((FECHA_HORA_SOLICITUD) <= (FECHA_HORA_RESPUESTA)) OR FECHA_HORA_RESPUESTA IS NULL));

CREATE TABLE PROPUESTA (
NOMBRE_CLUB VARCHAR2(60) NOT NULL,
NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
ID_DIRECTOR INT NOT NULL,
FECHA_HORA_PROPUESTA DATE NOT NULL,
ASUNTO VARCHAR2 (100) NOT NULL,
MENSAJE_TEXTO_PROPUESTA VARCHAR2(1500) NOT NULL,
FOREIGN KEY (TITULO,ID_DIRECTOR) REFERENCES PELICULA (TITULO,ID_DIRECTOR),
FOREIGN KEY (NOMBRE_CLUB,NOMBRE_USUARIO) REFERENCES MIEMBROS (NOMBRE_CLUB, NOMBRE_USUARIO_MIEMBRO),
PRIMARY KEY (NOMBRE_CLUB, NOMBRE_USUARIO, TITULO, ID_DIRECTOR,FECHA_HORA_PROPUESTA)
);

CREATE TABLE OPINION (
NOMBRE_CLUB VARCHAR2(60) NOT NULL,
NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
ID_DIRECTOR INT NOT NULL,
FECHA_HORA_OPINION DATE NOT NULL,
ASUNTO VARCHAR2(100) NOT NULL,
MENSAJE_TEXTO VARCHAR2(1500) NOT NULL,
PUNTUACION VARCHAR2 (100) NULL,
FOREIGN KEY (TITULO,ID_DIRECTOR) REFERENCES PELICULA (TITULO,ID_DIRECTOR),
FOREIGN KEY (NOMBRE_CLUB,NOMBRE_USUARIO) REFERENCES MIEMBROS (NOMBRE_CLUB, NOMBRE_USUARIO_MIEMBRO),
PRIMARY KEY (NOMBRE_CLUB, NOMBRE_USUARIO, TITULO, ID_DIRECTOR,FECHA_HORA_OPINION)
);

CREATE TABLE PELICULAS_VISTAS(
ID_CONTRATO VARCHAR2(16) NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
ID_DIRECTOR INT NOT NULL,
FECHA_HORA_VISTAS DATE NOT NULL,
FOREIGN KEY (TITULO,ID_DIRECTOR) REFERENCES PELICULA (TITULO,ID_DIRECTOR),
FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (ID_CONTRATO),
PRIMARY KEY (TITULO, ID_DIRECTOR,ID_CONTRATO,FECHA_HORA_VISTAS)
);